/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.Vaccine.Vaccine;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rangeshmurali
 */
public class ManageVaccineJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    
    public ManageVaccineJPanel(JPanel userProcessContainer, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) vaccineJTable.getModel();
        dtm.setRowCount(0);
        
        for(Vaccine vaccine : ecoSystem.getVaccineDirectory().getVaccineDirectory()){
            Object[] row = new Object[3];
            row[0] = vaccine;
            row[1] = vaccine.getVaccineId();
            row[2] = vaccine.getDiseasesName();
            
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vaccineJTable = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();
        removeVaccineJButton = new javax.swing.JButton();
        addVaccineJButton = new javax.swing.JButton();
        viewVaccineJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        vaccineIdJLabel = new javax.swing.JLabel();
        vaccineIdJTextField = new javax.swing.JTextField();
        searchVaccineJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Vaccine");

        vaccineJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Name", "Vaccine Id", "Diseases Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vaccineJTable);
        if (vaccineJTable.getColumnModel().getColumnCount() > 0) {
            vaccineJTable.getColumnModel().getColumn(0).setResizable(false);
            vaccineJTable.getColumnModel().getColumn(1).setResizable(false);
            vaccineJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        refreshJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        removeVaccineJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        removeVaccineJButton.setText("Remove Vaccine");
        removeVaccineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeVaccineJButtonActionPerformed(evt);
            }
        });

        addVaccineJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addVaccineJButton.setText("Add Vaccine");
        addVaccineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVaccineJButtonActionPerformed(evt);
            }
        });

        viewVaccineJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewVaccineJButton.setText("View Vaccine");
        viewVaccineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVaccineJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        vaccineIdJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vaccineIdJLabel.setText("Vaccine ID :");

        vaccineIdJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        searchVaccineJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchVaccineJButton.setText("Search Vaccine");
        searchVaccineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchVaccineJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(refreshJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(removeVaccineJButton)
                                    .addComponent(vaccineIdJLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vaccineIdJTextField)
                                    .addComponent(addVaccineJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(viewVaccineJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchVaccineJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(backJButton)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshJButton)
                    .addComponent(removeVaccineJButton)
                    .addComponent(addVaccineJButton)
                    .addComponent(viewVaccineJButton))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vaccineIdJLabel)
                    .addComponent(vaccineIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchVaccineJButton))
                .addGap(24, 24, 24)
                .addComponent(backJButton)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void removeVaccineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeVaccineJButtonActionPerformed
        int row = vaccineJTable.getSelectedRow();
        
        if(row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else { 
        
            Vaccine vaccine = (Vaccine)vaccineJTable.getValueAt(row, 0);
            
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int result = JOptionPane.showConfirmDialog(null, "Are you sure if you want to delete?", "warning", dialogButton);
            if(result == JOptionPane.YES_OPTION){
                ecoSystem.getVaccineDirectory().removeVaccine(vaccine);
                JOptionPane.showMessageDialog(null, "Vaccine is removed!", "Vaccine Supplier",JOptionPane.INFORMATION_MESSAGE);
                populateTable();
            }
            
        }
    }//GEN-LAST:event_removeVaccineJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addVaccineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVaccineJButtonActionPerformed
        AddVaccineJPanel addVaccineJPanel = new AddVaccineJPanel(userProcessContainer, ecoSystem);
        userProcessContainer.add("AddVaccineJPanel", addVaccineJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addVaccineJButtonActionPerformed

    private void viewVaccineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVaccineJButtonActionPerformed
        int row = vaccineJTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            Vaccine vaccine = (Vaccine)vaccineJTable.getValueAt(row, 0);
            ViewVaccineJPanel vpdjp = new ViewVaccineJPanel(userProcessContainer, vaccine);
            userProcessContainer.add("ViewVaccineJPanel", vpdjp);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_viewVaccineJButtonActionPerformed

    private void searchVaccineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchVaccineJButtonActionPerformed
        if(vaccineIdJTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please type the Vaccine ID to be searched.", "Search Vaccine", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try{ 
            Vaccine vaccine;
            int vaccineId = Integer.parseInt(vaccineIdJTextField.getText());
            vaccine = ecoSystem.getVaccineDirectory().searchVaccine(vaccineId);
            if (vaccine == null){
                JOptionPane.showMessageDialog(null, "Please Input a valid Vaccine ID", "Warning", JOptionPane.WARNING_MESSAGE);
                vaccineIdJTextField.setText(null);
                return;
            }
            ViewVaccineJPanel vpdjp = new ViewVaccineJPanel(userProcessContainer, vaccine);
            userProcessContainer.add("ViewVaccineJPanel", vpdjp);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Invalid VaccineID", "Search Vaccine", JOptionPane.WARNING_MESSAGE);
            vaccineIdJTextField.setText(null);
            return;
        }
    }//GEN-LAST:event_searchVaccineJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVaccineJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton removeVaccineJButton;
    private javax.swing.JButton searchVaccineJButton;
    private javax.swing.JLabel vaccineIdJLabel;
    private javax.swing.JTextField vaccineIdJTextField;
    private javax.swing.JTable vaccineJTable;
    private javax.swing.JButton viewVaccineJButton;
    // End of variables declaration//GEN-END:variables
}
