/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PharmacyWorkArea;

import Business.EcoSystem;
import Business.Enterprise.ProviderEnterprise;
import Business.Organization.OrderOrganization;
import Business.UserAccount.UserAccount;
import UserInterface.HospitalWorkArea.OrderVaccineJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rangeshmurali
 */
public class PharmacyOrderOrganiationWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private UserAccount userAccount;
    private OrderOrganization orderOrganization;
    private ProviderEnterprise providerEnterprise;
    
    public PharmacyOrderOrganiationWorkAreaJPanel(JPanel userProcessContainer, EcoSystem ecoSystem, UserAccount userAccount, OrderOrganization orderOrganization, ProviderEnterprise providerEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.userAccount = userAccount;
        this.orderOrganization = orderOrganization;
        this.providerEnterprise = providerEnterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        orderVaccineJButton = new javax.swing.JButton();
        viewOrderHistoryJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Pharmacy Order Organization Work Area");

        orderVaccineJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orderVaccineJButton.setText("Order Vaccine >>");
        orderVaccineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderVaccineJButtonActionPerformed(evt);
            }
        });

        viewOrderHistoryJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewOrderHistoryJButton.setText("View Order History >>");
        viewOrderHistoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderHistoryJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(230, 230, 230))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderVaccineJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(viewOrderHistoryJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(336, 336, 336))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(82, 82, 82)
                .addComponent(orderVaccineJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(viewOrderHistoryJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderVaccineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderVaccineJButtonActionPerformed
        try{
            if(userAccount.getEmployee().getPharmacy().getPharmacyStatus().equalsIgnoreCase("Approved")){
                OrderVaccineJPanel orderVaccineJPanel = new OrderVaccineJPanel(userProcessContainer, ecoSystem, userAccount, orderOrganization, providerEnterprise);
                userProcessContainer.add("OrderVaccineJPanel",orderVaccineJPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            } else if(userAccount.getEmployee().getPharmacy().getPharmacyStatus().equalsIgnoreCase("Rejected")){
                JOptionPane.showMessageDialog(null, "The Hospital registration has been REJECTED by State Public Health Department", "Hospital Rejected", JOptionPane.ERROR_MESSAGE);
                return;
            } else if(userAccount.getEmployee().getPharmacy().getPharmacyStatus().equalsIgnoreCase("Processing")){
                JOptionPane.showMessageDialog(null, "The hospital registration request is still pending with State Public Health Department", "Hospital Registration Pending", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Please send a hospital registration request to State Public Health Department", "Hospital Registration Not Initialized", JOptionPane.ERROR_MESSAGE);
            return;
        }

    }//GEN-LAST:event_orderVaccineJButtonActionPerformed

    private void viewOrderHistoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderHistoryJButtonActionPerformed
        ViewPharmacyOrderHistoryJPanel ohj = new ViewPharmacyOrderHistoryJPanel(userProcessContainer, userAccount);
        userProcessContainer.add("ViewPharmacyOrderHistoryJPanel", ohj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewOrderHistoryJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton orderVaccineJButton;
    private javax.swing.JButton viewOrderHistoryJButton;
    // End of variables declaration//GEN-END:variables
}
