/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.ProviderWorkArea;

import Business.Employee.Employee;
import Business.Enterprise.ProviderEnterprise;
import Business.Hospital.Hospital;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.Role.HospitalAdminRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rangeshmurali
 */
public class AddHospitalJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ProviderEnterprise providerEnterprise;
    
    public AddHospitalJPanel(JPanel userProcessContainer, ProviderEnterprise providerEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.providerEnterprise = providerEnterprise;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) hospitalJTable.getModel();
        dtm.setRowCount(0);
        
        for(Hospital hospital : providerEnterprise.getHospitalDirectory().getHospitalDirecotry()){
            Object[] row = new Object[3];
            row[0] = hospital;
            row[1] = hospital.getHospitalId();
            row[2] = hospital.getHospitalAddress();
            dtm.addRow(row);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hospitalJTable = new javax.swing.JTable();
        hospitalNameJLabel = new javax.swing.JLabel();
        hospitalAddressJLabel = new javax.swing.JLabel();
        hospitalNameJTextField = new javax.swing.JTextField();
        addHospitalJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        hospitalAddressJTextArea = new javax.swing.JTextArea();

        titleJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleJLabel.setText("Add Hospital");

        hospitalJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Hospital Name", "Hospital ID", "Hospital Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(hospitalJTable);
        if (hospitalJTable.getColumnModel().getColumnCount() > 0) {
            hospitalJTable.getColumnModel().getColumn(0).setResizable(false);
            hospitalJTable.getColumnModel().getColumn(1).setResizable(false);
            hospitalJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        hospitalNameJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hospitalNameJLabel.setText("Hospital Name :");

        hospitalAddressJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hospitalAddressJLabel.setText("Hospital Address :");

        hospitalNameJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        addHospitalJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addHospitalJButton.setText("Add Hospital");
        addHospitalJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHospitalJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        hospitalAddressJTextArea.setColumns(20);
        hospitalAddressJTextArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hospitalAddressJTextArea.setRows(5);
        jScrollPane2.setViewportView(hospitalAddressJTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(titleJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(hospitalNameJLabel)
                        .addGap(84, 84, 84)
                        .addComponent(hospitalNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(hospitalAddressJLabel)
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addComponent(addHospitalJButton))
                            .addComponent(backJButton))))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(hospitalNameJLabel))
                    .addComponent(hospitalNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hospitalAddressJLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(addHospitalJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(backJButton)
                .addContainerGap(558, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addHospitalJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHospitalJButtonActionPerformed
        String hospitalName = hospitalNameJTextField.getText();
        String hospitalAddress = hospitalAddressJTextArea.getText();
        
        Hospital hospital = providerEnterprise.getHospitalDirectory().createHospital();
        hospital.setHospitalAddress(hospitalAddress);
        hospital.setHospitalName(hospitalName);
        populateTable();
    }//GEN-LAST:event_addHospitalJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addHospitalJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel hospitalAddressJLabel;
    private javax.swing.JTextArea hospitalAddressJTextArea;
    private javax.swing.JTable hospitalJTable;
    private javax.swing.JLabel hospitalNameJLabel;
    private javax.swing.JTextField hospitalNameJTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
