/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.ProviderWorkArea;

import Business.Employee.Employee;
import Business.Enterprise.ProviderEnterprise;
import Business.Hospital.Hospital;
import Business.Pharmacy.Pharmacy;
import Business.Role.PharmacyAdminRole;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rangeshmurali
 */
public class AddPharmacyJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ProviderEnterprise providerEnterprise;
    
    public AddPharmacyJPanel(JPanel userProcessContainer, ProviderEnterprise providerEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.providerEnterprise = providerEnterprise;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) pharmacyJTable.getModel();
        dtm.setRowCount(0);
        
        for(Pharmacy pharmacy : providerEnterprise.getPharmacyDirectory().getPharmacyDirectory()){
            Object[] row = new Object[3];
            row[0] = pharmacy;
            row[1] = pharmacy.getPharmacyId();
            row[2] = pharmacy.getPharmacyAddress();
            dtm.addRow(row);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pharmacyNameJTextField = new javax.swing.JTextField();
        hospitalNameJLabel = new javax.swing.JLabel();
        hospitalAddressJLabel = new javax.swing.JLabel();
        titleJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pharmacyJTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        pharmacyAddressJTextArea = new javax.swing.JTextArea();
        addPharmacyJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        pharmacyNameJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        hospitalNameJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hospitalNameJLabel.setText("Pharmacy Name :");

        hospitalAddressJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hospitalAddressJLabel.setText("Pharmacy Address :");

        titleJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleJLabel.setText("Add Pharmacy");

        pharmacyJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Pharmacy Name", "Pharmacy ID", "Pharmacy Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pharmacyJTable);
        if (pharmacyJTable.getColumnModel().getColumnCount() > 0) {
            pharmacyJTable.getColumnModel().getColumn(0).setResizable(false);
            pharmacyJTable.getColumnModel().getColumn(1).setResizable(false);
            pharmacyJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        pharmacyAddressJTextArea.setColumns(20);
        pharmacyAddressJTextArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pharmacyAddressJTextArea.setRows(5);
        jScrollPane2.setViewportView(pharmacyAddressJTextArea);

        addPharmacyJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addPharmacyJButton.setText("Add Pharmacy");
        addPharmacyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPharmacyJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hospitalNameJLabel)
                            .addComponent(hospitalAddressJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pharmacyNameJTextField)
                            .addComponent(jScrollPane2))))
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(addPharmacyJButton)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(titleJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titleJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalNameJLabel)
                    .addComponent(pharmacyNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hospitalAddressJLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(addPharmacyJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(backJButton)
                .addContainerGap(263, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPharmacyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPharmacyJButtonActionPerformed
        String pharmacyName = pharmacyNameJTextField.getText();
        String pharmacyAddress = pharmacyAddressJTextArea.getText();

        Pharmacy pharmacy = providerEnterprise.getPharmacyDirectory().createPharmacy();
        pharmacy.setPharmacyName(pharmacyName);
        pharmacy.setPharmacyAddress(pharmacyAddress);
        populateTable();
    }//GEN-LAST:event_addPharmacyJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPharmacyJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel hospitalAddressJLabel;
    private javax.swing.JLabel hospitalNameJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea pharmacyAddressJTextArea;
    private javax.swing.JTable pharmacyJTable;
    private javax.swing.JTextField pharmacyNameJTextField;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
